# Example (Feature Engineering)

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_validate
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [9]:
df = pd.read_csv('Monthly_Transportation_Statistics_modified.csv', sep=',')
df = df.dropna()
df.head()

,Index,Date,Highway Fatalities Per 100 Million Vehicle Miles Traveled,Highway Fatalities,Transit Ridership - Other Transit Modes - Adjusted,Transit Ridership - Fixed Route Bus - Adjusted,Transit Ridership - Urban Rail - Adjusted,Freight Rail Intermodal Units,Freight Rail Carloads,State and Local Government Construction Spending - Breakwater/Jetty,...,Air Safety - Air Carrier Fatalities,U.S. Air Carrier Cargo (millions of revenue ton-miles) - International,Truck tonnage index,U.S. Air Carrier Cargo (millions of revenue ton-miles) - Domestic,Heavy truck sales SAAR (millions),Light truck sales SAAR (millions),Auto sales SAAR (millions),Transborder - Total North American Freight,Transborder - U.S. - Mexico Freight,Transborder - U.S. - Canada Freight
0,732,1/1/2008 0:00,1.22,8459,13911623,442844351,348756976,842973,1238122,50000000,...,0.0,1897167410,87.5,1.168018e+09,322000,7963000,7420000,7.558131e+10,28897924914,46683386800
1,735,4/1/2008 0:00,1.25,9435,15120273,472743286,387548619,892452,1326924,37000000,...,0.0,2184519616,86.6,1.230239e+09,337000,6942000,7326000,8.635952e+10,31907991127,54451524593
2,738,7/1/2008 0:00,1.33,9947,16530125,465258074,394473975,894970,1264217,69000000,...,1.0,1924038668,86.3,1.176962e+09,291000,5692000,7023000,8.607637e+10,33060251934,53016122791
3,741,10/1/2008 0:00,1.32,9582,16493417,515540107,404082236,946084,1315594,75000000,...,0.0,1959160995,82.9,1.182951e+09,267000,4972000,5694000,8.449930e+10,34515941934,49983355870
4,744,1/1/2009 0:00,1.09,7552,14517434,430468511,347843528,930248,1294266,38000000,...,0.0,1324523613,77.5,9.331066e+08,212000,5001000,4572000,5.426452e+10,22255716686,32008803519

In [11]:
X = df.drop('Highway Fatalities Per 100 Million Vehicle Miles Traveled', axis = 1)
y=df.

SyntaxError: invalid syntax (<ipython-input-11-793ffa41aea6>, line 2)

In [4]:
#engineer interaction features
poly = PolynomialFeatures(2, interaction_only = True, include_bias = False)
Xe = poly.fit_transform(X)
cols = poly.get_feature_names(X.columns)
Xe = pd.DataFrame(Xe, columns = cols)
Xe.head(3)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,...,total sulfur dioxide density,total sulfur dioxide pH,total sulfur dioxide sulphates,total sulfur dioxide alcohol,density pH,density sulphates,density alcohol,pH sulphates,pH alcohol,sulphates alcohol
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,...,33.9252,119.34,19.04,319.6,3.502278,0.558768,9.37932,1.9656,32.994,5.264
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,...,66.7856,214.40,45.56,656.6,3.189760,0.677824,9.76864,2.1760,31.360,6.664
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,...,53.8380,176.04,35.10,529.2,3.250220,0.648050,9.77060,2.1190,31.948,6.370

In [5]:
Xe = (Xe - Xe.mean())/Xe.std()

In [6]:
Xe['bias'] = 1
Xe.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,...,total sulfur dioxide pH,total sulfur dioxide sulphates,total sulfur dioxide alcohol,density pH,density sulphates,density alcohol,pH sulphates,pH alcohol,sulphates alcohol,bias
0,-0.528194,0.961576,-1.391037,-0.453077,-0.243630,-0.466047,-0.379014,0.558100,1.288240,-0.579025,...,-0.318888,-0.466169,-0.469886,1.330644,-0.575015,-0.959307,-0.393794,-0.368454,-0.837776,1
1,-0.298454,1.966827,-1.391037,0.043403,0.223805,0.872365,0.624168,0.028252,-0.719708,0.128910,...,0.567921,0.583123,0.535341,-0.727649,0.128665,-0.589072,0.003660,-0.756503,-0.110527,1
2,-0.298454,1.296660,-1.185699,-0.169374,0.096323,-0.083643,0.228975,0.134222,-0.331073,-0.048074,...,0.210063,0.169262,0.155323,-0.329450,-0.047314,-0.587208,-0.104015,-0.616863,-0.263249,1
3,1.654339,-1.384011,1.483689,-0.453077,-0.264878,0.107558,0.411372,0.664069,-0.978798,-0.461036,...,0.336563,0.157392,0.330716,-0.965278,-0.456379,-0.577888,-0.644658,-0.849597,-0.619601,1
4,-0.528194,0.961576,-1.391037,-0.453077,-0.243630,-0.466047,-0.379014,0.558100,1.288240,-0.579025,...,-0.318888,-0.466169,-0.469886,1.330644,-0.575015,-0.959307,-0.393794,-0.368454,-0.837776,1

In [7]:
lr = LinearRegression(fit_intercept=False)
cv_results = cross_validate(lr, Xe, Y, return_train_score = True)
R2_train = cv_results['train_score'].mean()
R2_valid = cv_results['test_score'].mean()
print('Train R2', R2_train.round(2))
print('Validation R2', R2_valid.round(2))

Train R2 0.43
Validation R2 0.25

In [9]:
lr.fit(Xe, Y)
coef = pd.Series(lr.coef_, index = Xe.columns)
coef.sort_values(ascending = False).head(10)

total sulfur dioxide           111.950530
free sulfur dioxide density     89.493996
sulphates                       64.908481
chlorides density               59.382580
citric acid density             30.382760
residual sugar                  15.652508
fixed acidity density           14.535287
density pH                      12.773722
density alcohol                  6.224390
bias                             5.636023
dtype: float64